Iter9
ilshat-fattakhov/go-yandex-metrics pull request #10
Opened 2024-05-26 15:37 UTC by ilshat-fattakhov

First commit

2024-05-28 08:27 UTC, s-shpak requested changes

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server.go
> +	FileStoragePath string `json:"file_storage_path"`
Почему это включено в конфигурацию сервера ? Это относится к конфигруации хранилища

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server.go
> +	FileStoragePath string `json:"file_storage_path"`
Почему это включено в конфигурацию сервера ? Это относится к конфигруации хранилища

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server.go
> +			lg.Info("Failed to load metrics")
Можем ли мы продолжить выполнение программы после этой ошибки ?

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server.go
> +		// r.Use(gzip.GzipHandle())
1. deadcode
2. middleware надо регистрировать при помощи `Use`, а не так, как это сделано, например, на строке 96

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server.go
> +		s.logger.Info("Cannot read storage file")
Как только возникла ошибка:
1. ее надо залоигровать (не терять значение `err`)
2. скорее всего выполнение функции надо завершить (кроме тех случаев, когда не надо: не надо, когда ошибка прокинута на самый верх и там обработана, т.е., в большинстве случаев, залогирована)

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
Мне не нравится текущая имплементация: бизнес-логика почему то занимается чтением и записью файла, которй хранит данные.

Хотелось бы, чтобы это было перенесено на слой работы с данными и:

1. Из конструктора хранилища возвращался объект общего интерфейса
2. Существовало две имплементации харинилища - in-memory и файловая
3. Файловое хранилище было оберткой надо in-memory: то есть встаривало бы in-memory при помощи композиции

В итоге сервису должно быть безразлично, сохраняем ли мы данные в файл или нет.

Если что-то непонятно из этого - уточни в пачке

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +func (s *Server) GetHandlerJSON(lg *zap.Logger) http.HandlerFunc {
Не очень хорошо, что ты определяешь дополнительный эдпоинт.

Лучше сделай один хендлер, который обрабатывает и запросы в json, и текстовые запросы. Их  логика практически одинаковая, кроме парсинга запроса и записи ответа

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +			panic(err)
Ну как же так :(

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +			lg.Info("Got error decoding JSON request")
Если ошибка не `InternalServerError`, то ошибку не надо логировать

2024-05-28 08:27 UTC, s-shpak commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
Если встроить `ResponseWriter` при помощи композиции, то не надо будет определять этот метод

2024-05-28 08:27 UTC, s-shpak commented on internal/gzip/gzip.go
> +		log.Fatal("cannot write to compressor")
Фаталиться из глубины кода нельзя

2024-05-28 08:27 UTC, s-shpak commented on internal/gzip/gzip.go
> +func (c *compressReader) Close() error {
1. `с.zr` также надо закрывать
2. обрати внимание, что `c.r` и `c.zr` - независимые ридеры, ошибка при закрытии одного не должна влиять на закрытие другого

2024-05-28 08:27 UTC, s-shpak commented on internal/gzip/gzip.go
> +		log.Printf("cannot read from compressReader: %v", err)
Здесь не надо логировать ошибку, т.к. при прочтении всего буфера будет всегда возникать ошибка. Просто передай ее наверх

2024-05-28 08:27 UTC, s-shpak commented on internal/gzip/gzip.go
> +					log.Printf("failed to close newCompressReader: %v", err)
Ты используешь `zap` для middleware, используй его везде в программе

2024-05-28 08:27 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +					log.Printf("failed to convert string to float64 value: %v", err)
Мы не можем использовать `mValue`, если возникла такая ошибка, т.к. значение будет невалидным

2024-05-28 08:27 UTC, s-shpak commented on internal/storage/storage.go
> +	Gauge   map[string]float64 `json:"gauge"`
Старайся все поля делать неэкспортируемыми по дефолту. Поле надо делать экспортируемым только если оно действительно используется внешним клиентом

2024-05-28 08:27 UTC, s-shpak commented on internal/storage/storage.go
> +	MemLock sync.Mutex         `json:"memlock"`
1. Лучше объявлять это поле указателем на мьютекс
2. Мьютексы точно не делают экспортируемыми

2024-05-28 08:27 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +func (a *Agent) SendMetricsJSONgzip(lg *zap.Logger) error {
Зачем оставлять агенту возможность посылать метрики не в JSON ?

2024-05-28 08:27 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +	// c := http.Client{Timeout: time.Duration(180) * time.Second}
deadcode

2024-05-28 08:27 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +	resp, err := c.Do(req)
Ошибку здесь надо проверять обязательно, как и код ответа

2024-05-28 08:27 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +	if resp != nil {
А вот тут проверка не нужна, т.к. если ошибка сверху = nil, то `resp` - валидный объект, с которым можно работать

2024-05-28 08:27 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +	req.Header.Set("Content-Length", fmt.Sprint(unsafe.Sizeof(metric)))
Не, `unsafe` исопльзовать не надо. Размер тела получается если посмотреть длину `buf`

2024-05-28 08:27 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +func (a *Agent) sendDataJSONgzip(c http.Client, v any, n string, mType string, method string) {
А где происходит сжатие запроса ?

2024-05-28 11:58 UTC, ilshat-fattakhov commented on .golangci.yml
> +#    - gofmt
Долго пытался устранить вот такие ошибки:

Text File is not `gofmt`-ed

в которых линтер предлагал заменить код на идентичный, как здесь:

Text File is not `gofmt`-ed
Severity error
SourceLines
package main

import (
	"log"

	"go-yandex-metrics/internal/agent/api"
	"go-yandex-metrics/internal/config"
	"go-yandex-metrics/internal/storage"
)

func main() {
	cfg, err := config.NewAgentConfig()
	if err != nil {
		log.Fatalf("failed to create config: %v", err)
	}

	store := storage.NewMemStorage()
	agent := api.NewAgent(cfg, store)

	err = agent.Start()
	if err != nil {
		log.Fatalf("failed to start agent %v", err)
	}
}
Replacement
NeedOnlyDelete false
NewLines
package main

import (
	"log"

	"go-yandex-metrics/internal/agent/api"
	"go-yandex-metrics/internal/config"
	"go-yandex-metrics/internal/storage"
)

func main() {
	cfg, err := config.NewAgentConfig()
	if err != nil {
		log.Fatalf("failed to create config: %v", err)
	}

	store := storage.NewMemStorage()
	agent := api.NewAgent(cfg, store)

	err = agent.Start()
	if err != nil {
		log.Fatalf("failed to start agent %v", err)
	}
}

В "Replacement" все совпадает до последней табуляции с SourceLines (я писал где-то в Пачке). 
Как с этим бороться?

2024-05-28 12:01 UTC, ilshat-fattakhov commented on go.mod
Пока обновил вручную, буду думать над .bat файлом

2024-05-28 12:09 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +			panic(err)
Ouch, осталось после поиска багов. Убираю/заменяю.

2024-05-28 13:06 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +func (a *Agent) sendDataJSONgzip(c http.Client, v any, n string, mType string, method string) {
В GzipMiddleware, а изначально было в этой функции, надо мне с названиями разобраться.

2024-05-28 13:08 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +		// r.Use(gzip.GzipHandle())
Я как раз думал что наоборот, хотел еще логгер так же завернуть туда, вроде:

		r.Post("/value/", LoggerMiddleware(gzip.GzipMiddleware(s.GetHandlerJSON(lg))))

Буду переделывать.

2024-05-28 13:11 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
> Мне не нравится текущая имплементация: бизнес-логика почему то 

Ну да, здесь пробелы в знаниях. Приходится гнать, чтобы успеть сдать работу, сосредотачиваться на более мелких вещах, нет времени посмотреть на все широким взглядом.

2024-05-28 13:12 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +func (s *Server) GetHandlerJSON(lg *zap.Logger) http.HandlerFunc {
Да, мысль такая было, даже начал делать, но в Пачке кто-то сказал что у них первые инкременты валятся из-за этого (вроде бы), отложил до поры, до времени. Похоже время настало! :O)

2024-05-28 16:02 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +		// r.Use(gzip.GzipHandle())
Доработал код GzipMiddleware и в итоге получилось вот так:

		r.Use(logger.Logger(lg))
		r.Use(gzip.GzipMiddleware())

2024-05-28 16:06 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +			lg.Info("Failed to load metrics")
Нет, поскольку нам передан флаг Restore со значением true, поэтому если мы не можем загрузить данные из файла, дальше идти нельзя, lg.Fatal(). Правильно?

lg.Fatal("Failed to load metrics", zap.Error(err))

2024-05-28 16:10 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +		s.logger.Info("Cannot read storage file")
А ведь это подсказка для ответа на один из предыдущих вопросов. Но я самостоятельно рассуждал, угадал, получается :O)
Или лучше:

return nil, err

вместо

lg.Fatal("Failed to load metrics", zap.Error(err))


?

2024-05-28 16:13 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +		s.logger.Info("Cannot read storage file")
Или

lg.Error("Failed to load metrics", zap.Error(err))
return nil, err

2024-05-29 09:10 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
Сделал, не уверен, что идеально.

2024-05-29 13:47 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +func (s *Server) GetHandlerJSON(lg *zap.Logger) http.HandlerFunc {
Сделал.

2024-05-29 14:12 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +func (s *Server) GetHandlerJSON(lg *zap.Logger) http.HandlerFunc {
Не могу сказать что получилось намного проще, как мне кажется, но эдпоинтов стало меньше.

2024-05-29 14:14 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +			lg.Info("Got error decoding JSON request")
Убрал.

2024-05-29 14:22 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
Тут нужна подсказка, даже не знаю, с чего начать.

2024-05-29 14:23 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +		log.Fatal("cannot write to compressor")
Исправил

2024-05-29 14:51 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
Посмотрел беседу в Пачке, но понял лишь частично. Эта часть понятна:

type compressWriter struct {
    http.ResponseWriter
    zw *gzip.Writer
}

но дальше появляется куча ошибок, которые пока не получается устранить.

2024-05-29 14:53 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
Пачка:

https://app.pachca.com/chats?thread_id=3751129

2024-05-29 15:09 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +		log.Printf("cannot read from compressReader: %v", err)
Передал вот так:

return 0, fmt.Errorf("cannot read from compressReader: %v", err)

2024-05-29 15:30 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +					log.Printf("failed to close newCompressReader: %v", err)
Вроде бы везде поменял на zap.

2024-05-29 15:33 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +					log.Printf("failed to convert string to float64 value: %v", err)
Фатальная ошибка, получается?

s.logger.Fatal(string(fmt.Sprintf("failed to convert string to float64 value: %v", err)))

и ниже:

s.logger.Fatal(string(fmt.Sprintf("failed to convert string to int64 value: %v", err)))

2024-05-29 15:43 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +	Gauge   map[string]float64 `json:"gauge"`
Пока не получается, если я делаю их неэкспортируемыми, они становятся невидимыми в других пакетах. Буду думать что делать дальше.
![nonexportable](https://github.com/ilshat-fattakhov/go-yandex-metrics/assets/837958/e8354ec8-31e5-47a8-88d7-8a00968644bc)

2024-05-29 15:44 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +	MemLock sync.Mutex         `json:"memlock"`
То же самое что и в ответе выше
![Uploading nonexportable.jpg…]()

2024-05-29 15:49 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +func (a *Agent) SendMetricsJSONgzip(lg *zap.Logger) error {
Ну да, это у сервера могут быть варианты JSON или HTML... Исправил.

2024-05-29 15:50 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +	// c := http.Client{Timeout: time.Duration(180) * time.Second}
No more deadcode! :O)

2024-05-29 16:00 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +	req.Header.Set("Content-Length", fmt.Sprint(unsafe.Sizeof(metric)))
binary.Size(&buf) или есть варианты еще?

2024-05-29 16:03 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +func (a *Agent) sendDataJSONgzip(c http.Client, v any, n string, mType string, method string) {
Поправил.

2024-05-30 08:28 UTC, ilshat-fattakhov commented on internal/logger/logger.go
> +	// defer func() {
Выполнил:

	defer func() {
		if err := logger.Sync(); err != nil {
			logger.Info(fmt.Sprintf("failed to sync logger: %v", err))
			return
		}
	}()

2024-05-30 08:41 UTC, ilshat-fattakhov commented on internal/logger/logger.go
> +func Logger(lg *zap.Logger) func(next http.Handler) http.Handler {
Перенес в cmd/server/middleware

2024-05-30 08:47 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +	resp, err := c.Do(req)
Сделал:

	if err != nil {
		a.logger.Info(fmt.Sprintf("failed to do a request: %v", err))
	}
Думаю fatal не нужно здесь, отправим данные в следующий раз

2024-05-30 08:48 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +	if resp != nil {
Ну тогда fatal нужен выше, получается?

2024-05-31 07:51 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +	resp, err := c.Do(req)
Сергей, вот так у меня, иначе тесты никак не проходятся:

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Content-Length", strconv.Itoa(binary.Size(&buf)))
	resp, _ := c.Do(req)
	// если раскомментировать строки ниже, автотест не проходится
	// с ошибкой "невозможно установить соединение с сервером"
	// if err != nil {
	// 	a.logger.Info(fmt.Sprintf("failed to do a request: %v", err))
	// }

	if resp != nil {
		_, _ = io.Copy(io.Discard, resp.Body)
		_ = resp.Body.Close()
	}

2024-06-02 19:56 UTC, s-shpak commented on cmd/server/main.go
> +		// log.Fatalf("failed to create config: %v", err)
deadcode

2024-06-02 19:56 UTC, s-shpak commented on cmd/server/middleware/logger.go
>  	// defer func() {
1. deadcode
2. Эту синхронизацию (через defer) можно поместить в `main`

2024-06-02 19:56 UTC, s-shpak commented on cmd/server/main.go
> +	store := storage.NewFileStorage()
А где возможность инициализировать in-memory store ?

2024-06-02 19:56 UTC, s-shpak commented on internal/logger/logger.go
> +func Logger(lg *zap.Logger) func(next http.Handler) http.Handler {
Зачем ? в `cmd` помещаются точки входа + минимальный код для запуска приложения. Middleware должны лежать рядом с роутером

2024-06-02 19:58 UTC, s-shpak commented on internal/logger/logger.go
> +				lg.Info("Error getting body")
1, 2 +
3. Как это ? Как мы можем продолжать выполнять запрос, если мы не смогли его прочесть ?

2024-06-02 20:01 UTC, s-shpak commented on internal/logger/logger.go
> +		return http.HandlerFunc(fn)
Сорри, нерпавильно написал: не создавай доп. переменную, просто оберни функцию в `http.HandlerFunc`

2024-06-02 20:02 UTC, s-shpak commented on internal/server/api/server.go
> +	FileStoragePath string `json:"file_storage_path"`
Почти: интервал созранения также относится к хранилищу

2024-06-02 20:02 UTC, s-shpak commented on internal/server/api/server.go
> +			lg.Info("Failed to load metrics")
Нет, неприавльно: фаталиться из глубины кода нельзя, потому что это сразу завершит процесс с ошибкой. Надо вернуть ошибку

2024-06-02 20:13 UTC, s-shpak requested changes

2024-06-02 20:13 UTC, s-shpak commented on internal/server/api/server.go
> +				store = storage.NewFileStorage()
Я не понимаю, что здеь происходит. Почему после ошибки происходит еще одна инициализация стора ? Почему вообще хранилище инициализируется здесь, а не в пакете, где лежит код хранилища ?

Одна из важных задача программиста -- строить корректные абстракции. Вот, например, пришел я читать код сервера. Как я пойму его, если в нем будел лежать все: инициализация хранилища, сбор конфигурации, настройка роутера и т.п. ? Намного лучше, если инициализация сервера будет вылядеть как-то так:

```go
store := NewStore(cfg.Store)
return &Server{
    store: store,
}
```

Детали построения компонентов надо заворачивать в абстракции, чтобы с кодом было проще работать: чтобы можно было думать о компонентах программы иерархически. Слона лучше есть по частям

2024-06-02 20:13 UTC, s-shpak commented on internal/server/api/server.go
> +	fmt.Println("Store: ", store)
Пожалуйста, вычитывайте код перед отправлением. Мы не раз обсуждали, что `fmt.Println` нельзя оставлять в финальной версии кода

2024-06-02 20:13 UTC, s-shpak commented on internal/server/api/server.go
> +			s.logger.Info(fmt.Sprintf("HTTP server has encountered an error: %v", err))
```suggestion
			s.logger.Infof("HTTP server has encountered an error: %v", err)
```

2024-06-02 20:13 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +				lg.Info(m.MType + " value doesn't exist for ID: " + m.ID)
1.

```suggestion
				lg.Infof(m.MType + " value doesn't exist for ID: " + m.ID)
```

2. Логируются только ошибки привоящие к статус-коду >= 500

2024-06-02 20:13 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +						s.logger.Fatal(fmt.Sprintf("failed to convert string to float64 value: %v", err))
Фаталиться из глубины кода нельзя

2024-06-02 20:13 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +	fmt.Println("Memstorage for counter:")
--

2024-06-02 20:13 UTC, s-shpak commented on internal/storage/storage.go
> +	MemLock sync.Mutex         `json:"memlock"`
А что в ответе выше ? Не вижу картинку

2024-06-02 20:13 UTC, s-shpak commented on internal/storage/storage.go
> +	FileStoragePath string `json:"file_storage_path"`
Почему это поле экспортируемо ? По умолчанию поля структру лучше делать неэкспортируемыми. Экспортируемыми надо делать только те поля, которые реально используются извне

2024-06-02 20:13 UTC, s-shpak commented on internal/server/api/server.go
> +	StoreInterval uint64 `json:"store_interval"`
Я не нашел реализацию асинхронной записи в коде

2024-06-02 20:17 UTC, s-shpak commented on internal/server/api/server.go
> +		s.logger.Info("Cannot read storage file")
Ошибки прокидываются наверх до тех пор, пока их нельзя будет обработать. Часто обработка ошибки - ее логирование.

То есть если ошибка возникла при обработки запроса пользователя, она докидывается до кода, который отвечает за ответ пользователю и там превращается в ответ (если это внутренняя ошибка, то еще и логируется). Если ошибка произошла при инициализации, например, то прокидывается наверх до точки входа, там логируется и приводит к заверению процесса.

Фаталиться из глубины кода нельзя: fatal сразу завершает процесс, что не позволит выполнить, например, graceful shutdown. Потому ошибка прокидывается на самый верх.

Если что-то непонятно в плане работы с ошибками, то спросите еще в пачке

2024-06-02 20:18 UTC, s-shpak commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
Не, не идеально, будем исправлять потихоньку (в том числе в следующем ревью)

2024-06-02 20:22 UTC, s-shpak commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
А какого рода ошибки ?

2024-06-02 20:22 UTC, s-shpak commented on internal/gzip/gzip.go
> +func (c *compressReader) Close() error {
См. здесь: https://app.pachca.com/chats/9384000?message=250966571

2024-06-02 20:22 UTC, s-shpak commented on internal/gzip/gzip.go
> +		log.Printf("cannot read from compressReader: %v", err)
Это неверно, надо так:

```go
return 0, fmt.Errorf("cannot read from compressReader: %w", err)
```

См. здест почему: https://go.dev/blog/go1.13-errors

2024-06-02 20:22 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +					log.Printf("failed to convert string to float64 value: %v", err)
Нет, см. комментарии выше

2024-06-02 20:23 UTC, s-shpak commented on internal/storage/storage.go
> +	Gauge   map[string]float64 `json:"gauge"`
Ну так, например, мьютекс и не должен экспортироваться. Работай с ним только из этого пакета (в методах, которые определены в этом пакете)

2024-06-02 20:24 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +	resp, err := c.Do(req)
Надо разбираться в чем дело

2024-06-02 20:24 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +	if resp != nil {
нет, нужно отправить ошибку наверх

2024-06-02 20:26 UTC, s-shpak commented on internal/agent/api/agent_handlers.go
> +	req.Header.Set("Content-Length", fmt.Sprint(unsafe.Sizeof(metric)))
Нет, смотри документацию к `Buffer`: https://pkg.go.dev/bytes

2024-06-02 20:27 UTC, s-shpak requested changes
См. добавленные комментарии

2024-06-03 02:10 UTC, ilshat-fattakhov commented
Сергей добрый день!

 

Вот сводка линтера и файлы

 

Ильшат

 

From: s-shpak ***@***.*** 
Sent: Monday, June 3, 2024 3:53 AM
To: ilshat-fattakhov/go-yandex-metrics
Cc: ilshat-fattakhov; Author
Subject: Re: [ilshat-fattakhov/go-yandex-metrics] Iter9 (PR #10)

 

@s-shpak commented on this pull request.

  _____  

In .golangci.yml <https://github.com/ilshat-fattakhov/go-yandex-metrics/pull/10#discussion_r1623642655> :

> @@ -493,8 +493,8 @@ linters:
     - goconst
     - gocritic
     - godot
-    - gofmt
-    - goimports
+#    - gofmt

Пришли код (файлом, не копируя), на который ругается линтер, пожалуйста

—
Reply to this email directly, view it on GitHub <https://github.com/ilshat-fattakhov/go-yandex-metrics/pull/10#discussion_r1623642655> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAGMSRU5AALV7O5TNPMJA7TZFNZ2PAVCNFSM6AAAAABIJ4TCDOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOJSGU4TQNJYG4> .
You are receiving this because you authored the thread.  <https://github.com/notifications/beacon/AAGMSRQEAWU4JKD2SRPFEJ3ZFNZ2PA5CNFSM6AAAAABIJ4TCDOWGG33NNVSW45C7OR4XAZNRKB2WY3CSMVYXKZLTORJGK5TJMV32UY3PNVWWK3TUL5UWJTT4XKCTW.gif> Message ID: ***@***.***>

2024-06-03 02:11 UTC, ilshat-fattakhov commented on .golangci.yml
> +#    - gofmt
[files.zip](https://github.com/user-attachments/files/15528002/files.zip)

2024-06-03 02:12 UTC, ilshat-fattakhov commented on .golangci.yml
> +#    - gofmt
Еще отправил zip по почте

2024-06-03 02:14 UTC, ilshat-fattakhov commented on internal/logger/logger.go
> +func Logger(lg *zap.Logger) func(next http.Handler) http.Handler {
>Зачем ?
Подсмотрел у Николая Тузова, у него в папку http-server лежит папка middleware :O)

2024-06-03 02:16 UTC, ilshat-fattakhov commented on internal/logger/logger.go
> +func Logger(lg *zap.Logger) func(next http.Handler) http.Handler {
>куда-то рядом с роутером
Просмотрел ключевое слово "роутер"!

2024-06-03 04:08 UTC, ilshat-fattakhov commented on internal/logger/logger.go
> +func Logger(lg *zap.Logger) func(next http.Handler) http.Handler {
>В серверный main.go можно поместить инициализацию роутера, 
С этим пока не разобрался, вожможно вернусь сюда позже по ходу исправления ошибок

>а логику middleware к роутеру
перенес в 

go-yandex-metrics\internal\server\middleware\logger.go

роутер лежит в 

go-yandex-metrics\internal\server\api\server.go

2024-06-03 04:15 UTC, ilshat-fattakhov commented on internal/logger/logger.go
> +				lg.Info("Error getting body")
log.Fatal("error getting request body", err) выручит на здесь? Передать ошибку выше мы не можем ведь здесь:

func Logger(lg *zap.Logger) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {

2024-06-03 13:12 UTC, ilshat-fattakhov commented on internal/logger/logger.go
> +		return http.HandlerFunc(fn)
Обернул:

return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

2024-06-03 13:18 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	FileStoragePath string `json:"file_storage_path"`
Теперь так:

type StorageCfg struct {
	FileStoragePath string `json:"file_storage_path"`
	StoreInterval   uint64 `json:"store_interval"`
}

2024-06-03 13:31 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +		s.logger.Info("Cannot read storage file")
Вот так должно быть, как я понял (залогировал и вернул ошибку наверх):

lg.Info(fmt.Sprintf("cannot read storage file: %v", err))
return nil, fmt.Errorf("cannot read storage file: %w", err)

2024-06-03 15:08 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
На рисунке попыталья объяснить
![composition](https://github.com/ilshat-fattakhov/go-yandex-metrics/assets/837958/815e8fdf-75da-4d8a-b5cd-e484a0785afb)

2024-06-03 15:13 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +func (c *compressReader) Close() error {
У меня ссылка не выходит на сообщение, Пачка образает ее до https://app.pachca.com/chats/9384000
Поиск ничего не дал, в Пачке он вообще ничего не находит.

2024-06-03 15:15 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +		log.Printf("cannot read from compressReader: %v", err)
Исправил, прочитал.

2024-06-03 15:34 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +					log.Printf("failed to convert string to float64 value: %v", err)
Здесь не могу понять как пробросить ошибку наверх, ведь хэндлер ничего не возвращает:

func (s *Server) GetHandler(lg *zap.Logger) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {

2024-06-04 05:24 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
>Мне не нравится текущая имплементация: бизнес-логика почему то занимается чтением и записью файла, которй хранит данные.

Вот этот момент вроде сделал, остальные (1,2,3) пока нет, не хватает знаний, курю Интернет.

2024-06-04 05:25 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +	Gauge   map[string]float64 `json:"gauge"`
Сделал с мьютексом так, как описано выше.

2024-06-04 11:11 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +	req.Header.Set("Content-Length", fmt.Sprint(unsafe.Sizeof(metric)))
вот так получилось: req.Header.Set("Content-Length", strconv.Itoa(buf.Len()))

2024-06-04 11:12 UTC, ilshat-fattakhov commented on cmd/server/main.go
> +		// log.Fatalf("failed to create config: %v", err)
Раскомментировал

2024-06-04 11:16 UTC, ilshat-fattakhov commented on cmd/server/middleware/logger.go
>  	// defer func() {
Поместил.

2024-06-04 11:26 UTC, ilshat-fattakhov commented on cmd/server/main.go
> +	store := storage.NewFileStorage()
У меня он автоматически инициализируется внутри FileStorage:

func NewMemStorage() *MemStorage {
	return &MemStorage{
		Gauge:   make(map[string]float64),
		Counter: make(map[string]int64),
	}
}

func NewFileStorage() *FileStorage {
	memStore := NewMemStorage()
	return &FileStorage{
		memStore,
		"",
	}
}

или это не так?

2024-06-04 11:29 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +				store = storage.NewFileStorage()
>Почему после ошибки происходит еще одна инициализация стора ?
Сейчас уже сам не помню точно, но идея была если из файла не удалось инициализировать, то инициализировать в памяти. Это исправлено при исправлении других ошибок.

2024-06-04 12:16 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +				store = storage.NewFileStorage()
>Одна из важных задача программиста -- строить корректные абстракции.

С этим пока плохо, Сергей!

2024-06-04 15:14 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +				store = storage.NewFileStorage()
>Одна из важных задача программиста -- строить корректные абстракции.

Можно мне взять 1:1 с вами по этой теме?

2024-06-05 08:40 UTC, ilshat-fattakhov commented on cmd/server/main.go
> +		// log.Fatalf("failed to create config: %v", err)
Убрал

2024-06-05 08:40 UTC, ilshat-fattakhov commented on cmd/server/middleware/logger.go
>  	// defer func() {
Перенес в main

2024-06-05 08:44 UTC, ilshat-fattakhov commented on cmd/server/main.go
> +	store := storage.NewFileStorage()
Перенес в /server/server.go и переделал вот так:

	store, err := storage.NewStore(cfg)

>А где возможность инициализировать in-memory store ?

Здесь нужна помощь

2024-06-05 08:47 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +				store = storage.NewFileStorage()
>Как я пойму его, если в нем будел лежать все: инициализация хранилища, сбор конфигурации, настройка роутера и т.п. ?

Вот эту часть доработал, но не идеально, думаю. Перенес в storage.go функции сохранения, в server_handlers.go оставил только функции хэндлера и т.п.

2024-06-05 08:51 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	fmt.Println("Store: ", store)
Прошу прощения, гнал лошадей чтобы успеть к дэдлайну сдачи на ревью

2024-06-05 08:53 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +			s.logger.Info(fmt.Sprintf("HTTP server has encountered an error: %v", err))
Сработало без ошибок только так:

s.logger.Info(fmt.Sprintf("HTTP server has encountered an error: %v", err))

2024-06-05 08:55 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +				lg.Info(m.MType + " value doesn't exist for ID: " + m.ID)
Убрал

2024-06-05 08:57 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +						s.logger.Fatal(fmt.Sprintf("failed to convert string to float64 value: %v", err))
Не знаю как передать ошибку из хэндлера выше, сделал так:

s.logger.Info(fmt.Sprintf("failed to convert string to float64 value: %v", err))

2024-06-05 09:01 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +						s.logger.Fatal(fmt.Sprintf("failed to convert string to float64 value: %v", err))
И в итоге:

2024-06-05 09:01 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +						s.logger.Fatal(fmt.Sprintf("failed to convert string to float64 value: %v", err))
s.logger.Info(fmt.Sprintf("failed to convert string to float64 value: %v", err))
w.WriteHeader(http.StatusInternalServerError)
return

2024-06-05 09:02 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +	fmt.Println("Memstorage for counter:")
Убрал

2024-06-05 09:11 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +	FileStoragePath string `json:"file_storage_path"`
Попробовал сделать его неэкспортируемым

fileStoragePath 

и оно стало невидимым в других пакетах. Нужна помощь.

2024-06-05 09:12 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	StoreInterval uint64 `json:"store_interval"`
>Я не нашел реализацию асинхронной записи в коде

Вы видимо имеете ввиду вот это:

func saveData(s *Server) {
	if s.cfg.StorageCfg.StoreInterval != 0 && s.cfg.StorageCfg.FileStoragePath != "" {
		go func() {
			tickerStore := time.NewTicker(time.Duration(s.cfg.StorageCfg.StoreInterval) * time.Second)
			for range tickerStore.C {
				err := (*storage.Store).Save(s.store, s.cfg.StorageCfg.FileStoragePath)
				if err != nil {
					s.logger.Info(fmt.Sprintf("failed to store metrics: %v", err))
					return
				}
			}
		}()
	}
}

и да, этот код не попал в коммит. Сейчас он там.

2024-06-06 18:10 UTC, s-shpak commented on internal/logger/logger.go
> +				lg.Info("Error getting body")
Значит надо ответить пользователю и закончить обработку запроса

2024-06-06 18:16 UTC, s-shpak commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
Первая ссылка по запросу "how to embed structs in go": https://gobyexample.com/struct-embedding

2024-06-06 18:18 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +					log.Printf("failed to convert string to float64 value: %v", err)
1. Фаталиться можно только из `main`
2. Ошибку надо пробросить максимално наверх и обработать. Здесь логичная обработка - отдать ответ пользователю с подходящим статус-кодом (и, возможно, залогировать ошибку)

2024-06-06 18:21 UTC, s-shpak commented on internal/server/api/server.go
> +				store = storage.NewFileStorage()
1-1 кончено можно брать

2024-06-06 18:22 UTC, s-shpak commented on internal/storage/storage.go
> +	FileStoragePath string `json:"file_storage_path"`
А зачем каким-то пакетам его видеть ? Когда я пишу какой-то комментарий, это не значит, что выполнение моего предложения не сломает существующий код. Кода надо адаптировать

2024-06-06 18:23 UTC, s-shpak requested changes

2024-06-06 18:23 UTC, s-shpak commented on cmd/agent/main.go
> +		log.Panicf("failed to create config: %v", err)
Паниковать нельзя

2024-06-06 18:24 UTC, s-shpak commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
Возможно, стоит взять 1-1, либо сформулировать, что именно не понятно и задать вопрос

2024-06-07 02:50 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +		log.Panicf("failed to create config: %v", err)
Да, Сергей, я это помню. Это я устранял ошибку локального линтера:

Issues
FromLinter gocritic
Text exitAfterDefer: log.Fatalf will exit, and `defer func(){...}(...)` will not run
Severity error
SourceLines
		log.Fatalf("failed to create config: %v", err)
Replacement
Pos
Filename cmd\agent\main.go

2024-06-07 02:51 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +		log.Panicf("failed to create config: %v", err)
Сейчас проверил, Гитхаб то же самое выдает

2024-06-07 02:54 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +		log.Panicf("failed to create config: %v", err)
Я устранял ошибку, на которую вы указали выше:

>Эту синхронизацию (через defer) можно поместить в main

но видимо не так как надо. Может вернуть defer назад?

2024-06-07 03:06 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +	FileStoragePath string `json:"file_storage_path"`
Я его добываю из /storage/file.go, а заполняется оно в config.go при запуске сервера. Если делаю неэкспортирумым, т.е. меняю FileStoragePath на fileStoragePath, то в /storage/file.go не могу его добыть (вложил снимок экрана). Не могу пока придумать что-то еще.

![fileStoragePath](https://github.com/ilshat-fattakhov/go-yandex-metrics/assets/837958/f07401f0-f167-4e93-a7a1-9a1e417c3235)

2024-06-07 03:19 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +	if resp != nil {
Здесь мистика какая-то, нужно 1:1 посмотреть. Когда я раскомментирую вот это:

	//if err != nil {
	//	a.logger.Info(fmt.Sprintf("failed to do a request: %v", err))
	//	return fmt.Errorf("failed to do a request: %w", err)
	//}

валятся тесты

2024-06-07 03:22 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +					log.Printf("failed to convert string to float64 value: %v", err)
Так и сделал:

s.logger.Info(fmt.Sprintf("failed to convert string to float64 value: %v", err))
w.WriteHeader(http.StatusInternalServerError)
return

2024-06-07 08:41 UTC, ilshat-fattakhov commented on internal/logger/logger.go
> +				lg.Info("Error getting body")
Ответил вот так:

lg.Error("error getting request body", zap.Error(err))
ww.WriteHeader(http.StatusInternalServerError)
return

2024-06-07 08:53 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +		s.logger.Info("Cannot read storage file")
>Нет, ошибка логируется там, где заканичвается ее путь наверх.

Вот то, что мне надо было знать про ошибки! Убрал логирование там, где можно было прокинуть ошибки выше, где нельзя - вернул http.Status...

2024-06-07 08:55 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
>Существовало две имплементации харинилища - in-memory и файловая

 В крайнем коммите так и сделал (но он не проходит автотесты пока)

2024-06-07 08:56 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
>Файловое хранилище было оберткой надо in-memory: то есть встаривало бы in-memory при помощи композиции

Мне кажется у меня так теперь и есть:

type FileStorage struct {
	MemStore *MemStorage `json:"data"`
	savePath string
}

func (f *FileStorage) GetMetric(mType, mName string) (string, error) {
	return f.MemStore.GetMetric(mType, mName)
}

2024-06-07 08:57 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
Но нужен ваш профессиональный взгляд!

2024-06-07 15:40 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
Про композицию хорошо вот здесь зашло:

https://golangify.com/composition-and-forwarding

но пока туплю в плане применения в моем случае. Изучаю дальше.

2024-06-07 16:03 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +func (c *compressWriter) Header() http.Header {
Похоже гора таки родила мышь, сейчас залью на Гитхаб.

2024-06-11 14:15 UTC, ilshat-fattakhov commented on internal/agent/api/agent_handlers.go
> +	if resp != nil {
Сергей добрый день!
Удалось докопаться до истины, как мне кажется. После тщательного логирования выяснилось, что автотест запускает сервер на доли секунды позже того, как агент пытается отправить данные на сервер:

{"level":"info","ts":1718034715.3206372,"caller":"api/agent.go:59","msg":"sending metrics"}
{"level":"info","ts":1718034715.3388147,"caller":"api/agent.go:62","msg":"failed to send metrics: an error occured sending gauge data: failed to do a request:  Post \"http://localhost:8080/update/\": EOF"}
{"level":"info","ts":1718034715.3548768,"caller":"api/server.go:69","msg":"starting server"}

Вот это и заставляло агент упасть, вернее моя неправильная обрабаботка ошибки. Я прокинул ошибку почти на самый верх, но не стал ее прокидывать в main т.к. после этого агент падал, сделал так:

		case <-tickerSend.C:
			err := a.sendMetrics()
			if err != nil {
				a.logger.Info("failed to send metrics: %w", zap.Error(err))
			}
		}

Я полагаю что такой код позволяет агенту выстоять и попытаться отправить данные через очередные ReportInterval секунд, а также позволяет ему пережить временные падения сервера.
Что скажете?

2024-06-11 14:18 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	data, err := os.ReadFile(s.cfg.FileStoragePath)
Сделал еще один подход здесь, если делаю memStore неэкспортируемым, получаю ошибку:

struct type 'go-yandex-metrics/internal/storage.FileStorage' doesn't have any exported fields, nor custom marshaling (SA9005)go-staticcheck

и не могу загрузить данные из JSON файла. Оставил это поле экспортируемым.

2024-06-11 14:19 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +		s.logger.Info("Cannot read storage file")
Убрал fmt.Sprintf из обработки ошибок

2024-06-11 16:01 UTC, s-shpak requested changes

2024-06-11 16:01 UTC, s-shpak commented on internal/gzip/gzip.go
> +			lg, err := logger.InitLogger()
Не надо создавать логгер каждый раз: лучше объявить `GzipMiddleware` как метод и добавить логгер в структуру, с которой этот метод ассоциирован

2024-06-11 16:01 UTC, s-shpak commented on internal/agent/api/agent.go
> +				a.logger.Info("failed to send metrics: %w", zap.Error(err))
Да, отличный подход! Только кажется, что это лучше логгировать на уровне `Error`

2024-06-11 16:11 UTC, ilshat-fattakhov commented on internal/agent/api/agent.go
> +				a.logger.Info("failed to send metrics: %w", zap.Error(err))
Woo-hoo! Спасибо Сергей! У меня уже первый час ночи, завтра "first thing in the morning", как говорится :O)

2024-06-13 08:02 UTC, ilshat-fattakhov commented on internal/gzip/gzip.go
> +			lg, err := logger.InitLogger()
Сделал так, как вы подсказали. Надеюсь правильно! :O)

2024-06-14 10:59 UTC, s-shpak approved these changes

2024-06-20 00:52 UTC, merged