Iter13
ilshat-fattakhov/go-yandex-metrics pull request #14
Opened 2024-06-14 08:11 UTC by ilshat-fattakhov

First commit

2024-06-19 14:43 UTC, s-shpak requested changes

2024-06-19 14:43 UTC, s-shpak commented on internal/agent/api/agent.go
> +			err := a.sendMetrics()
Совместите это действие с логикой ретраев. То есть логика начиная со строки 66 должна делать первый запрос к серверу

2024-06-19 14:43 UTC, s-shpak commented on internal/agent/api/agent.go
> +				if a.cfg.ReportInterval > 1 {
Можно использовать https://github.com/hashicorp/go-retryablehttp вместо написания своего инструмента ретраев

2024-06-19 14:43 UTC, s-shpak commented on internal/agent/api/agent.go
> +						time.Sleep(time.Duration(i) * time.Second)
Интервал можно рассчитать один раз

2024-06-19 14:43 UTC, s-shpak commented on internal/agent/api/agent_funcs.go
> +			a.logger.Warn(GaugeType + " is not float64")
Если вы возвращаете ошибку, то не надо ее здесь же логировать

2024-06-19 14:43 UTC, s-shpak commented on internal/agent/api/agent_funcs.go
> +			return fmt.Errorf("an error occured sending gauge data: %w", err)
Я бы не стал выходить из функции здесь: лучше залогировать ошибку и отправить следующую метрику

2024-06-19 14:43 UTC, s-shpak commented on internal/server/api/handlers_test.go
> +			// r := httptest.NewRequest(tt.method, tt.url, http.NoBody)
deadcode

2024-06-19 14:43 UTC, s-shpak commented on internal/server/api/server.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
Лишний импорт

2024-06-19 14:43 UTC, s-shpak commented on internal/server/middleware/logger.go
> +	// logger, err := zap.NewProduction()
deadcode

2024-06-19 14:43 UTC, s-shpak commented on internal/storage/db.go
> +CREATE TABLE IF NOT EXISTS gaugemetrics (
Используйте миграции, как обсуждали на вебинаре: https://github.com/s-shpak/webinar-migrations

2024-06-19 14:43 UTC, s-shpak commented on internal/storage/db.go
> +	metricName VARCHAR (25) UNIQUE NOT NULL,
Добаьте индексы к тем полям, которые учатсвуют в операциях с БД

2024-06-19 14:43 UTC, s-shpak commented on internal/storage/db.go
> +	db, err := sql.Open("pgx", databaseDSN)
Настоятельно рекомендую использовать `pgxpool` вместо интерфейса `database/sql`. См. материалы к вебинару здесь: https://github.com/s-shpak/yabinar-3.1-postgres

Исползовать `database/sql` не запрещено, но в реальном мире все используют `pgx` напрямую. Так удобнее

2024-06-19 14:43 UTC, s-shpak commented on internal/storage/db.go
> +	for err != nil {
Надо ли ретраить любую ошибку при пинге ?

2024-06-19 14:43 UTC, s-shpak commented on internal/storage/store.go
> +		return nil, errors.New("error creating storage")
А какая ошибка возникла ?

2024-06-20 04:31 UTC, ilshat-fattakhov commented on internal/agent/api/agent.go
> +				if a.cfg.ReportInterval > 1 {
Попробовал retryablehttp, довольно легко прикручивается:

func NewAgent(cfg config.AgentCfg, store *MemStorage) (*Agent, error) {
	lg, err := logger.InitLogger()
	if err != nil {
		return nil, fmt.Errorf("failed to init logger: %w", err)
	}
	retryClient := retryablehttp.NewClient()
	retryClient.RetryMax = 3
	retryClient.RetryWaitMin = 1 * time.Second
	retryClient.RetryWaitMax = 5 * time.Second
	standardClient := retryClient.StandardClient() // *http.Client

	agt := &Agent{
		logger: lg,
		store:  store,
		client: standardClient,
		cfg:    cfg,
	}
	return agt, nil
}

Но интервалы между попытками он рассчитывает по своей замороченной логике, и я не смог настроить интервалы как в ТЗ:

Интервалы между повторами должны увеличиваться: 1s, 3s, 5s.

У меня retryablehttp с такими настройками:

retryClient.RetryWaitMin = 1 * time.Second
retryClient.RetryWaitMax = 5 * time.Second

выдает 1s, 2s и 4s:

2024/06/20 12:09:53 [DEBUG] POST http://localhost:8080/updates/
2024/06/20 12:09:53 [ERR] POST http://localhost:8080/updates/ request failed: ...
2024/06/20 12:09:53 [DEBUG] POST http://localhost:8080/updates/: retrying in 1s (3 left)
2024/06/20 12:09:54 [ERR] POST http://localhost:8080/updates/ request failed: ...
2024/06/20 12:09:54 [DEBUG] POST http://localhost:8080/updates/: retrying in 2s (2 left)
2024/06/20 12:09:56 [ERR] POST http://localhost:8080/updates/ request failed:...
2024/06/20 12:09:56 [DEBUG] POST http://localhost:8080/updates/: retrying in 4s (1 left)
2024/06/20 12:10:00 [ERR] POST http://localhost:8080/updates/ request failed: ...

а с настройками:

retryClient.RetryWaitMin = 2 * time.Second
retryClient.RetryWaitMax = 5 * time.Second

выдает 2s, 4s и 5s. Не знаю что и делать (в смысле использовать retryablehttp или нет)

2024-06-20 04:48 UTC, ilshat-fattakhov commented on internal/agent/api/agent.go
> +			err := a.sendMetrics()
Исправил

2024-06-20 04:57 UTC, ilshat-fattakhov commented on internal/agent/api/agent.go
> +						time.Sleep(time.Duration(i) * time.Second)
Не совсем понял, Сергей - с каждой итерацией у меня время сна меняется, на первой итерации это одна секунда, на второй - три секудны, на третьей - пять секунд...
Или надо чтобы были константы и использовать их здесь:

err := a.sendMetrics()

и здесь:

err := a.sendMetricsBatch()

?

2024-06-20 04:59 UTC, ilshat-fattakhov commented on internal/agent/api/agent_funcs.go
> +			a.logger.Warn(GaugeType + " is not float64")
Прошу прощения, просмотрел. Я хорошо запомнил, что мы или логируем ошибку, или возвращаем ее.

2024-06-20 05:04 UTC, ilshat-fattakhov commented on internal/agent/api/agent_funcs.go
> +			return fmt.Errorf("an error occured sending gauge data: %w", err)
Залогировал:

a.logger.Info("an error occured sending gauge data", zap.Error(err))
и
a.logger.Info("an error occured sending counter data", zap.Error(err))

2024-06-20 05:05 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
Убрал

2024-06-20 05:05 UTC, ilshat-fattakhov commented on internal/server/middleware/logger.go
> +	// logger, err := zap.NewProduction()
Убрал deadcode

2024-06-20 08:56 UTC, ilshat-fattakhov commented on internal/storage/db.go
> +	db, err := sql.Open("pgx", databaseDSN)
Перешел на pgxpool, разобрался, что если используем разные драйверы SQL то нужно database/sql, если только postgres, то pgxpool дает больше возможностей

2024-06-20 09:00 UTC, ilshat-fattakhov commented on internal/storage/db.go
> +CREATE TABLE IF NOT EXISTS gaugemetrics (
Использовал миграцию. Завис немного пока не разобрался что имя файла должно быть:

00001_init.up.sql
а не 
00001_init_up.sql

как у меня было. Выяснил вот таким образом:

	if err := m.Up(); err != nil {
		if errors.Is(err, migrate.ErrNoChange) {
			lg.Info("failed to apply migrations:", zap.Error(err))
		} else {
			return fmt.Errorf("failed to apply migrations to the DB: %w", err)
		}
	}

У вас на видео вот этой ветки нет:

	} else {
			return fmt.Errorf("failed to apply migrations to the DB: %w", err)
		}

пришлось искать ответ в сети после того как добавить веточку.

2024-06-20 10:07 UTC, ilshat-fattakhov commented on internal/storage/db.go
> +	metricName VARCHAR (25) UNIQUE NOT NULL,
Сделал через golang-migrate, создал файл 00002_create_indexes.up:

BEGIN TRANSACTION;

CREATE INDEX IF NOT EXISTS gaugeidx
ON gaugemetrics(metricname);

CREATE INDEX IF NOT EXISTS counteridx
ON countermetrics(metricname);

COMMIT;

Или надо было создать индекс при создании таблиц?

2024-06-20 10:11 UTC, ilshat-fattakhov commented on internal/storage/db.go
> +	metricName VARCHAR (25) UNIQUE NOT NULL,
По ходу дела выяснил что имя индекса в Postgres должно быть уникально для базы данных (в MySQL - для таблицы).
Помучился с тестированием миграций (постоянно выходила ошибка ErrNoChange) пока не понял что нужно удалить таблицу schema_migrations чтобы заново протестировать.

2024-06-20 11:35 UTC, ilshat-fattakhov commented on internal/storage/db.go
> +	for err != nil {
После перехода на pgxpool эта функция оказалась ненужной...

2024-06-20 11:52 UTC, ilshat-fattakhov commented on internal/storage/store.go
> +		return nil, errors.New("error creating storage")
По умолчанию нужно создавать memory storage, так и сделал:

	default:
		store, err := NewMemStorage(cfg)
		if err != nil {
			return nil, fmt.Errorf("error creating memory storage: %w", err)
		}
		return store, nil

2024-06-20 15:09 UTC, ilshat-fattakhov commented on internal/server/api/handlers_test.go
> +			// r := httptest.NewRequest(tt.method, tt.url, http.NoBody)
Переписал тест-функцию

2024-06-21 21:12 UTC, s-shpak commented on internal/agent/api/agent.go
> +						time.Sleep(time.Duration(i) * time.Second)
Прошу прощения, не так прочитал логику

2024-06-21 21:16 UTC, s-shpak commented on internal/agent/api/agent.go
> +				if a.cfg.ReportInterval > 1 {
Если вы решите использовать эту библиотеку, то интервал настраивается при помощи вот этого: https://pkg.go.dev/github.com/hashicorp/go-retryablehttp#Backoff . Необходимо определить свою функцию и передать ее в клиент: https://pkg.go.dev/github.com/hashicorp/go-retryablehttp#Client

Если нет, то просто зарезолвьте этот комментарий

2024-06-21 21:17 UTC, s-shpak commented on internal/storage/db.go
> +CREATE TABLE IF NOT EXISTS gaugemetrics (
Если вы посмотрите код еще раз, то увидите, что там такая проверка:

```go
if !errors.Is(err, migrate.ErrNoChange)
```

То есть мы обрабатываем все ошибки кроме `ErrNoChange`: ее мы игнорируем

2024-06-21 21:18 UTC, s-shpak commented on internal/storage/db.go
> +	metricName VARCHAR (25) UNIQUE NOT NULL,
На самом деле все можно поместить в одну и ту же миграцию: это первая версия приложения с БД, потому можно создать только один файл миграции

2024-06-21 21:19 UTC, s-shpak requested changes
См. комментарии

2024-06-22 03:51 UTC, ilshat-fattakhov commented on internal/agent/api/agent.go
> +				if a.cfg.ReportInterval > 1 {
Спасибо за подсказку, добавил функцию Backoff:

func Backoff(minValue, maxValue time.Duration, attemptNum int, resp *http.Response) time.Duration {
	switch attemptNum {
	case 0:
		return 1 * time.Second
	case 1:
		return 3 * time.Second
	case 2:
		return 5 * time.Second
	default:
		return 3 * time.Second
	}
}

Надо было внимательнее читать спецификацию.

2024-06-22 03:58 UTC, ilshat-fattakhov commented on internal/storage/db.go
> +CREATE TABLE IF NOT EXISTS gaugemetrics (
Просмотрел восклицательный знак, на видео не разглядел :O)

2024-06-22 04:16 UTC, ilshat-fattakhov commented on internal/storage/db.go
> +	metricName VARCHAR (25) UNIQUE NOT NULL,
Переделал на один файл. Два файла делал больше для себя, чтобы увидеть как работает миграция, ну и думал так тоже можно.

2024-07-08 07:19 UTC, merged