Iter5
ilshat-fattakhov/go-yandex-metrics pull request #6
Opened 2024-05-04 08:55 UTC by ilshat-fattakhov

First commit iteration 5

2024-05-05 13:39 UTC, s-shpak reviewed
Добавь линтер в Github Actions: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions

2024-05-05 13:39 UTC, s-shpak commented on internal/storage/vscode-tutorial.code-workspace
Зачем этот файл ?

2024-05-05 13:39 UTC, s-shpak commented on go.mod
> +go 1.19.1
```suggestion
go 1.22.2
```

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/main.go
> +var logger = slog.New(slog.NewTextHandler(os.Stdout, nil))
Глобальные переменные не нужны. Инициализируй логгер в функции и передавай его туда, куда нужно

2024-05-05 13:39 UTC, s-shpak commented on internal/storage/flags.go
> +func ParseFlags() {
Почему эта функция находится в пакете `storage` ?

2024-05-05 13:39 UTC, s-shpak commented on internal/storage/flags.go
> +var RunAddr string
Глобальные переменные не нужны: объяви структуру `Config` и возвращай ее

2024-05-05 13:39 UTC, s-shpak commented on internal/storage/flags.go
> +	//os.Setenv("ADDRESS", "localhost:9999")
deadcode

2024-05-05 13:39 UTC, s-shpak commented on internal/storage/flags.go
> +		fmt.Println("Using environment value: " + paramValue)
Не используй `fmt`, используй `log`

2024-05-05 13:39 UTC, s-shpak commented on internal/storage/flags.go
> +func IsFlagPassed(name string) bool {
Зачем экспортировать эту функцию ?

2024-05-05 13:39 UTC, s-shpak commented on internal/storage/flags.go
> +	} else if IsFlagPassed(flagName) {
Зачем такая сложная логика: ты уже получил флаги в функции `ParseFlags`

2024-05-05 13:39 UTC, s-shpak commented on internal/storage/flags.go
> +	if paramValue := os.Getenv(envParamName); paramValue != "" {
Лучше использовать https://pkg.go.dev/os#LookupEnv

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/main.go
> +func main() {
В `main` слишком много логики, перенеси ее в `internal`

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/main.go
> +	pollInterval, err := strconv.ParseUint(storage.PollInterval, 10, 64)
Это можно сделать при получении конифгурации

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/main.go
> +		log.Fatal(err)
Стоит пояснить, что именно произогло:


```suggestion
		log.Fatal("failed to parse %s as a report interval value: %v", storage.ReportInterval, err)
```

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/main.go
> +			go save.SaveMetrics(m)
Горутины не нужны, мы это обсудили на 1-1

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/main.go
> +	runtime.ReadMemStats(m)
Ты получаешь метрики один раз, при запуске программы. Они могу изменяться, именно поэтому тебе надо их собирать каждый раз по тикеру `SaveMetrics`

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/handlers/send/send.go
> +	for n := range storage.CounterMetrics {
Не очень понимаю, что здесь происходит. Агент, при каждом сборе метрик должен увеличивать `PollCounter` на 1, при отправке сбрасывать это значение в 0

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/handlers/send/send.go
> +		url := "http://" + storage.RunAddr + "/update/gauge/" + n + "/" + fmt.Sprintf("%v", v)
1. Лучше использовать https://pkg.go.dev/net/url#JoinPath
2. Преобразовывай численные значения в строковые представления при помощи пакета `strconv`

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/handlers/send/send.go
> +		resp, err := c.Do(req)
Стоит проверить статус-код ответа

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/handlers/send/send_test.go
> +		// TODO: Add test cases.
Если этот тест ничего не делает, то его надо удалить

2024-05-05 13:39 UTC, s-shpak commented on cmd/agent/handlers/save/save_test.go
> +		// TODO: Add test cases.
Аналогично

2024-05-05 13:39 UTC, s-shpak commented on cmd/server/main.go
> +func main() {
Слишком много кода в `main`, вынеси в `internal`

2024-05-05 13:39 UTC, s-shpak commented on cmd/server/main.go
> +	log.Fatal(http.ListenAndServe(runAddr, r))
Это неправильно, смотри видео про ошибки: https://app.pachca.com/chats/9180496?message=234290731

2024-05-05 13:39 UTC, s-shpak commented on cmd/server/main.go
> +	if r.Method != http.MethodGet {
Эту проверку за тебя делает `chi`

2024-05-05 13:39 UTC, s-shpak commented on cmd/server/main.go
> +	// По запросу GET http://<АДРЕС_СЕРВЕРА>/ сервер должен отдавать HTML-страницу
Используй этот пакет для формирования страницы: https://pkg.go.dev/html/template

2024-05-08 07:56 UTC, ilshat-fattakhov commented on internal/storage/vscode-tutorial.code-workspace
My fault! Убрал.

2024-05-08 07:57 UTC, ilshat-fattakhov commented on go.mod
> +go 1.19.1
Исправил.

2024-05-08 07:59 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +var logger = slog.New(slog.NewTextHandler(os.Stdout, nil))
Сначала сделал как вы посоветовали, затем полностью убрал все вызовы логгера т.к. линтер требовал контекста.

2024-05-08 08:00 UTC, ilshat-fattakhov commented on internal/storage/flags.go
> +func ParseFlags() {
Переделал, до этого поместил туда, т.к. не было конфига отдельного.

2024-05-08 08:01 UTC, ilshat-fattakhov commented on internal/storage/flags.go
> +var RunAddr string
Попробовал (в файле cmd/config/config.go), посмотрите, пожалуйста.

2024-05-08 08:02 UTC, ilshat-fattakhov commented on internal/storage/flags.go
> +	//os.Setenv("ADDRESS", "localhost:9999")
Убрал!

2024-05-08 08:03 UTC, ilshat-fattakhov commented on internal/storage/flags.go
> +		fmt.Println("Using environment value: " + paramValue)
Да, я уже понял. Убрав вообще все.

2024-05-08 08:04 UTC, ilshat-fattakhov commented on internal/storage/flags.go
> +func IsFlagPassed(name string) bool {
Вроде как хороший способ определить передан какой-либо флаг или нет. Нашел в сети.

2024-05-08 08:05 UTC, ilshat-fattakhov commented on internal/storage/flags.go
> +	} else if IsFlagPassed(flagName) {
Тут не совсем разобрался.

2024-05-08 08:05 UTC, ilshat-fattakhov commented on internal/storage/flags.go
> +	if paramValue := os.Getenv(envParamName); paramValue != "" {
Ouch! Просмотрел этот комментарий! Сегодня попробую переделать.

2024-05-08 08:06 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +func main() {
Да, я понял, перенес.

2024-05-08 08:07 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +	pollInterval, err := strconv.ParseUint(storage.PollInterval, 10, 64)
Я переписал, не уверен что идеально. (cmd/config/config.go

2024-05-08 08:10 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +		log.Fatal(err)
Вот так видимо неправильно:

return fmt.Errorf("error parsing ReportInterval: %w", err)

?

2024-05-08 09:27 UTC, ilshat-fattakhov commented on cmd/agent/handlers/send/send.go
> +	for n := range storage.CounterMetrics {
То есть в нем всегда будет 1?

2024-05-08 09:29 UTC, ilshat-fattakhov commented on cmd/agent/handlers/send/send.go
> +		url := "http://" + storage.RunAddr + "/update/gauge/" + n + "/" + fmt.Sprintf("%v", v)
Переделаю c JoinPath. strconv использую в последнем коммите по подсказке линтера почти везде, здесь просмотрел.

2024-05-08 09:29 UTC, ilshat-fattakhov commented on cmd/agent/handlers/send/send.go
> +		resp, err := c.Do(req)
Буду делать!

2024-05-08 09:29 UTC, ilshat-fattakhov commented on cmd/agent/handlers/send/send_test.go
> +		// TODO: Add test cases.
Убрал.

2024-05-08 09:30 UTC, ilshat-fattakhov commented on cmd/agent/handlers/save/save_test.go
> +		// TODO: Add test cases.
Убрал.

2024-05-08 09:30 UTC, ilshat-fattakhov commented on cmd/server/main.go
> +	log.Fatal(http.ListenAndServe(runAddr, r))
Да, я посмотрел видео, переделал.

2024-05-08 09:31 UTC, ilshat-fattakhov commented on cmd/server/main.go
> +	if r.Method != http.MethodGet {
Сначала не понял, где, потом разобрался:

	r.Get("/value/{mtype}/{mname}", handlers.GetHandler)

2024-05-08 09:36 UTC, ilshat-fattakhov commented on cmd/server/main.go
> +	// По запросу GET http://<АДРЕС_СЕРВЕРА>/ сервер должен отдавать HTML-страницу
Использовал 	"text/template" т.к. не удалось вывести в браузер HTML, со всеми нужными заголовками выводил исходный HTML. Нашел в сети что это в целях безопасности.

В ходе тестирования на гите выяснил, что автотесты (Iteration3) не ждут мой красивый HTML во такого вида:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{.Title}}</title>
</head>
<body>
<div>
    {{.HTML}}
</div>
</body>
</html>

а хотят видеть просто цифру, поэтому в HTML шаблоне у меня просто

{{.HTML}}

2024-05-08 14:02 UTC, ilshat-fattakhov commented on internal/storage/flags.go
> +func IsFlagPassed(name string) bool {
Разобрался с этим, сделал по другому.

2024-05-08 14:03 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +			go save.SaveMetrics(m)
Сделал commit.

2024-05-08 14:09 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +		log.Fatal(err)
Сделал как вы советуете.

2024-05-08 14:22 UTC, ilshat-fattakhov commented on cmd/agent/handlers/send/send.go
> +		url := "http://" + storage.RunAddr + "/update/gauge/" + n + "/" + fmt.Sprintf("%v", v)
Update: здесь не получается т.к. мне нужно преобразовать Float to String. Взял здесь:

https://yourbasic.org/golang/convert-string-to-float/

Float to string
Use the [fmt.Sprintf](https://golang.org/pkg/fmt/#Sprintf) method to format a floating-point number as a string.

2024-05-08 14:23 UTC, ilshat-fattakhov commented on cmd/agent/handlers/send/send.go
> +		url := "http://" + storage.RunAddr + "/update/gauge/" + n + "/" + fmt.Sprintf("%v", v)
JoinPath добавил.

2024-05-08 14:25 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +		log.Fatal(err)
Сделал:
log.Fatal(fmt.Printf("failed to parse %s as a report interval value: %v", cfg.Agent.ReportInterval, err))

2024-05-08 14:40 UTC, ilshat-fattakhov commented on cmd/agent/handlers/send/send.go
> +		resp, err := c.Do(req)
Сделал.

2024-05-09 06:50 UTC, ilshat-fattakhov commented on cmd/agent/handlers/send/send.go
> +	for n := range storage.CounterMetrics {
Понял что к чему, исправляю.

2024-05-10 06:22 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +	runtime.ReadMemStats(m)
Разобрался наконец, как мне кажется, сейчас будет коммит.

2024-05-10 14:53 UTC, s-shpak requested changes
Настрой `golangci-lint` для запуска при помощи Github Actions, см. здесь как https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions. Поправь проблемы, которые линтер обнаружит

Обрати внимание, что я пометил не все проблемные места в коде: если одна и та же ошибка встречается несколько раз, то надо поправить ее везде

Не резольв комменты - оставляй их мне, так мне легче понять, что именно изменилось

2024-05-10 14:53 UTC, s-shpak commented on cmd/agent/handlers/handlers.go
> +	pollInterval, err := strconv.ParseUint(cfg.Agent.PollInterval, 10, 64)
Лучше убрать это в конфигурацию

2024-05-10 14:53 UTC, s-shpak commented on cmd/agent/handlers/handlers.go
> +		log.Fatal(fmt.Printf("failed to parse %s as a report interval value: %v", cfg.Agent.ReportInterval, err))
Ошибки надо возвращать наверх

2024-05-10 14:53 UTC, s-shpak commented on cmd/agent/handlers/handlers.go
> +		sendURL, err := url.JoinPath(base, path)
Ты можешь передавать в эту функцию произвольное количество аргументов

2024-05-10 14:53 UTC, s-shpak commented on cmd/agent/handlers/handlers.go
> +		// logger.Info("Sending gauge metrics to " + sendUrl)
deadcode

2024-05-10 14:53 UTC, s-shpak commented on cmd/config/config.go
> +		Host           string `yaml:"host"`
А зачем эти структурные теги ?

2024-05-10 14:53 UTC, s-shpak commented on cmd/config/config.go
> +	} else {
Подумай, как убрать этот (и другие подобные) `else`

2024-05-10 14:53 UTC, s-shpak commented on cmd/server/handlers/handlers.go
> +var MetricsDB = storage.NewMemStorage()
Глобальные переменные не нужны

2024-05-10 14:53 UTC, s-shpak commented on cmd/server/handlers/handlers.go
> +	// html := HTMLPage{"All Metrics", getAllMetrics()}
deadcode

2024-05-10 14:53 UTC, s-shpak commented on cmd/server/handlers/handlers.go
> +	cwd, _ := os.Getwd()
Ошибки надо проверять

2024-05-10 14:53 UTC, s-shpak commented on cmd/server/handlers/handlers.go
> +	pathToT := filepath.Join(cwd, "cmd","server","templates","metrics.txt")
Лучше добавить содержимое файлов в этот же файл (либо использовать https://pkg.go.dev/embed)

2024-05-10 14:53 UTC, s-shpak commented on cmd/server/handlers/handlers.go
> +	err = t.Execute(w, html)
Зачем это ? Используй `w.Write()`

2024-05-10 14:53 UTC, s-shpak commented on internal/storage/storage.go
> +var GaugeMetrics = map[string]float64{
Глобальные переменные не нужны

2024-05-10 15:50 UTC, ilshat-fattakhov commented on cmd/config/config.go
> +		Host           string `yaml:"host"`
Остались от кода который нашел в сети. Убираю.

2024-05-10 15:56 UTC, ilshat-fattakhov commented on cmd/config/config.go
> +	} else {
Решил что так:

	config.Server.Host = flagRunAddr
	envRunAddr, ok := os.LookupEnv("ADDRESS")
	if ok {
		config.Server.Host = envRunAddr
	}

2024-05-10 15:58 UTC, ilshat-fattakhov commented on cmd/server/handlers/handlers.go
> +	cwd, _ := os.Getwd()
Сделал, будет в коммите.

2024-05-11 01:54 UTC, ilshat-fattakhov commented on cmd/agent/handlers/handlers.go
> +	pollInterval, err := strconv.ParseUint(cfg.Agent.PollInterval, 10, 64)
Затупил с этим:

Настрой golangci-lint для запуска при помощи Github Actions

т.к. просмотрел что это нужно сделать не локально, а на Гитхабе. На Гитхабе более щадящие правила. Локально больше ошибок выдает.

2024-05-11 01:56 UTC, ilshat-fattakhov commented on cmd/agent/handlers/handlers.go
> +	pollInterval, err := strconv.ParseUint(cfg.Agent.PollInterval, 10, 64)
Насчет:

Не резольв комменты - оставляй их мне, так мне легче понять, что именно изменилось

восстановил (unresolved) комментарии предыдущей проверки. Я был уверен что команда resolve дает возможность проверяющему увидеть мои комментарии.

2024-05-11 05:02 UTC, ilshat-fattakhov commented on cmd/agent/handlers/handlers.go
> +	pollInterval, err := strconv.ParseUint(cfg.Agent.PollInterval, 10, 64)
Лучше убрать это в конфигурацию

Убрал, возможно не совсем правильно, посмотрите, пожалуйста.

2024-05-11 05:06 UTC, ilshat-fattakhov commented on cmd/agent/handlers/handlers.go
> +		log.Fatal(fmt.Printf("failed to parse %s as a report interval value: %v", cfg.Agent.ReportInterval, err))
Вернул вот так:

			return nil, fmt.Errorf("failed to parse %d as a report interval value: %v", ReportInterval, err)

2024-05-11 09:56 UTC, ilshat-fattakhov commented on cmd/agent/handlers/handlers.go
> +		sendURL, err := url.JoinPath(base, path)
Точно! Как filepath.Join

2024-05-11 10:39 UTC, ilshat-fattakhov commented on cmd/server/handlers/handlers.go
> +	err = t.Execute(w, html)
Пока не могу понять как использовать w.Write()

В примерах используют t.Execute(w, html)

        data := "Go Template"
        tmpl, _ := template.New("data").Parse("<h1>{{ .}}</h1>")
        tmpl.Execute(w, data)

2024-05-11 10:40 UTC, ilshat-fattakhov commented on cmd/server/handlers/handlers.go
> +	pathToT := filepath.Join(cwd, "cmd","server","templates","metrics.txt")
Добавил. 

	tpl := "{{.HTML}}"

2024-05-11 11:28 UTC, ilshat-fattakhov commented on cmd/server/handlers/handlers.go
> +	err = t.Execute(w, html)
Сергей, вот это будет костыль?

	var doc bytes.Buffer
	err = t.Execute(&doc, allMetrics)
	if err != nil {
		fmt.Println(err)
	}
	html := doc.String()
	w.Write([]byte(html))

2024-05-11 11:29 UTC, ilshat-fattakhov commented on cmd/server/handlers/handlers.go
> +	pathToT := filepath.Join(cwd, "cmd","server","templates","metrics.txt")
Поменял в итоге на tpl := "{{.}}"

2024-05-11 11:30 UTC, ilshat-fattakhov commented on cmd/agent/handlers/handlers.go
> +		sendURL, err := url.JoinPath(base, path)
sendURL, err := url.JoinPath("http://", host, "update", "counter", n, "/", value)

2024-05-11 11:30 UTC, ilshat-fattakhov commented on cmd/agent/handlers/handlers.go
> +		// logger.Info("Sending gauge metrics to " + sendUrl)
Убрал.

2024-05-11 11:49 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +var GaugeMetrics = map[string]float64{
Думаю как это реализовать

2024-05-12 08:32 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +var GaugeMetrics = map[string]float64{
Обошелся без var GaugeMetrics

2024-05-12 08:32 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +var GaugeMetrics = map[string]float64{
В смысле убрал совсем.

2024-05-12 08:35 UTC, ilshat-fattakhov commented on cmd/server/handlers/handlers.go
> +var MetricsDB = storage.NewMemStorage()
Нашел кое-что в сети, переписал довольно много кода, надеюсь все сделал более-менее правильно

2024-05-13 21:57 UTC, s-shpak requested changes
В `cmd` должны лежать только точки входа. Перенесите всю логику в `internal`

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/api/agent.go
> +				return fmt.Errorf("failed to save metrics: %w", err)
Если не получилось сохранить метрики, то стоит залогировать ошибку и продолжить выполнение процесса, не надо завершаться с ошибкой

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/api/agent.go
> +				return fmt.Errorf("failed to send metrics: %w", err)
См. выше

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/api/config.go
> +type Agent struct {
Странно, что эта структура лежит в этом файле. Лучше поместить ее в `agent.go`

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/api/config.go
> +	HTTPAgent
Не понимаю, зачем использовать здесь композицию. Просто перенесите поля из `HTTPAgent` в `Configuration`

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/api/config.go
> +	var defaultRunAddr = "localhost:8080"
Все дефолтные значения можно сделать константами

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/api/config.go
> +	var RunAddr string
Локальные переменные не принято называть с большой буквы

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/api/handlers.go
> +		err = resp.Body.Close()
Лучше вызвать это при помощи `defer` на строке 73

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/main.go
> +		log.Fatal("failed to create config: %w", err)
```suggestion
		log.Fatalf("failed to create config: %v", err)
```

2024-05-13 21:57 UTC, s-shpak commented on cmd/agent/api/handlers.go
> +		sendURL, err := url.JoinPath("http://", a.cfg.Host, "update", "gauge", n, "/", value)
```suggestion
		sendURL, err := url.JoinPath("http://", a.cfg.Host, "update", "gauge", n, value)
```

2024-05-13 21:57 UTC, s-shpak commented on cmd/server/api/handlers.go
> +		// if errors.Is(err, ErrItemNotFound) {
deadcode

2024-05-13 21:57 UTC, s-shpak commented on cmd/server/api/handlers.go
> +	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
Не создавайте логгер каждый раз - используйте глобальный из пакета `log` (log.Println). Кастомный будет добавлен в следующих спринтах

2024-05-14 08:23 UTC, ilshat-fattakhov commented on cmd/agent/api/agent.go
> +				return fmt.Errorf("failed to save metrics: %w", err)
>В cmd должны лежать только точки входа. Перенесите всю логику в internal
Понял! Делал быстро, чтобы успеть получить еще парочку ревью до жесткого дэдлайна :O)
Переношу.
>Если не получилось сохранить метрики, то стоит залогировать ошибку и продолжить выполнение процесса, не 
>надо завершаться с ошибкой
Да, это логично, конечно. Был в цейтноте (см. выше), торопился! :O)

2024-05-14 08:36 UTC, ilshat-fattakhov commented on cmd/server/api/handlers.go
> +	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
Понятно, исправил.

2024-05-14 08:36 UTC, ilshat-fattakhov commented on cmd/server/api/handlers.go
> +		// if errors.Is(err, ErrItemNotFound) {
Убрал

2024-05-14 08:38 UTC, ilshat-fattakhov commented on cmd/agent/api/handlers.go
> +		sendURL, err := url.JoinPath("http://", a.cfg.Host, "update", "gauge", n, "/", value)
Ну да, смешно - использую url.JoinPath чтобы избавиться от разделителей пути и добавляю разделитель в аргументы :O)
Исправил

2024-05-14 08:39 UTC, ilshat-fattakhov commented on cmd/agent/main.go
> +		log.Fatal("failed to create config: %w", err)
Исправил, спасибо за подсказку

2024-05-14 09:02 UTC, ilshat-fattakhov commented on cmd/agent/api/handlers.go
> +		err = resp.Body.Close()
Сделал

2024-05-14 09:02 UTC, ilshat-fattakhov commented on cmd/agent/api/config.go
> +	var RunAddr string
Помню это, просмотрел

2024-05-14 09:04 UTC, ilshat-fattakhov commented on cmd/agent/api/config.go
> +	var defaultRunAddr = "localhost:8080"
Сделал

2024-05-14 14:23 UTC, ilshat-fattakhov commented on cmd/agent/api/config.go
> +type Agent struct {
Поместил ее туда, куда нужно, как мне кажется. Дело в том, что я переделал структуру папок и файлов, и файла agent.go больше нет

2024-05-14 14:24 UTC, ilshat-fattakhov commented on cmd/agent/api/agent.go
> +				return fmt.Errorf("failed to send metrics: %w", err)
Сделал

2024-05-14 14:25 UTC, ilshat-fattakhov commented on cmd/agent/api/config.go
> +	HTTPAgent
Изначально взял пример из сети. Сейчас переделал:

type AgentCfg struct {
	Host           string
	PollInterval   uint64
	ReportInterval uint64
}

2024-05-14 14:26 UTC, ilshat-fattakhov commented on cmd/agent/api/config.go
> +	var RunAddr string
Исправил

2024-05-14 14:26 UTC, ilshat-fattakhov commented on cmd/agent/api/handlers.go
> +		err = resp.Body.Close()
Вот так:

		defer func() {
			if err := resp.Body.Close(); err != nil {
				log.Println("failed to close response body: %w", err)
				return
			}
		}()
чтобы получить ошибку - нашел в сети

2024-05-15 23:37 UTC, s-shpak requested changes

2024-05-15 23:37 UTC, s-shpak commented on internal/api/api.go
> +func NewAgent(cfg AgentCfg, store *storage.MemStorage) *Agent {
Поместить агент и сервер вместе - плохая идея, мне кажется. Разнеси код сервера и агента по разным пакетам

2024-05-15 23:37 UTC, s-shpak commented on internal/api/api.go
> +func NewAgent(cfg AgentCfg, store *storage.MemStorage) *Agent {
Поместить агент и сервер вместе - плохая идея, мне кажется. Разнесите код сервера и агента по разным пакетам

2024-05-15 23:37 UTC, s-shpak commented on internal/api/api.go
> +				log.Println("failed to save metrics: %w", err)
```suggestion
				log.Printf("failed to save metrics: %v", err)
```

2024-05-16 06:23 UTC, ilshat-fattakhov commented on internal/api/api.go
> +				log.Println("failed to save metrics: %w", err)
Спасибо за подсказку!

2024-05-16 06:23 UTC, ilshat-fattakhov commented on internal/api/api.go
> +func NewAgent(cfg AgentCfg, store *storage.MemStorage) *Agent {
Разделил, надеюсь что правильно

2024-05-16 06:23 UTC, ilshat-fattakhov commented on internal/api/api.go
> +func NewAgent(cfg AgentCfg, store *storage.MemStorage) *Agent {
Разделил, надеюсь что правильно

2024-05-16 08:56 UTC, s-shpak requested changes

2024-05-16 08:56 UTC, s-shpak commented on internal/api/agent.go
> +				log.Println("failed to save metrics: %w", err)
```suggestion
				log.Printf("failed to save metrics: %v", err)
```

Обратите внимание, что в коде есть и другие места с этой проблемой. Поправьте их, пожалуйста

2024-05-16 08:56 UTC, s-shpak commented on internal/api/agent.go
> +package api
Пакет определяется здесь. Сейчас и сервер, и агент лежат в одном и том же пакете. Лучше создать такую арзитектуру:

- internal
    - agent
    - server
    
В папке `agent` лежит код агента, в папке `server` - сервера. В идеале, внутри папки сервера есть такая арзитектура, например:

- server
    - api
    - service
    - storage

Посмотрите первый вебинар, чтобы лучше понять, как именно можно структурировать проект (вот пример: https://github.com/s-shpak/webinar-architecture-in-Go)

2024-05-16 09:05 UTC, ilshat-fattakhov commented on internal/api/agent.go
> +				log.Println("failed to save metrics: %w", err)
Прощу прощения - я "сломал" гитхаб у себя на компьютере, и эти изменения пропали (я снова заливал iter5 с гитхаба после "поломки"), и не догадался их проверить перед отправкой.

2024-05-16 09:07 UTC, ilshat-fattakhov commented on internal/api/agent.go
> +				log.Println("failed to save metrics: %w", err)
Поправил

2024-05-16 09:09 UTC, ilshat-fattakhov commented on internal/api/agent.go
> +package api
Я пытался сделать красиво, с папками как в вашем примере, но не смог решить проблему "невидимости" структур

type ServerCfg struct {
	Host string
}

type AgentCfg struct {
	Host           string
	PollInterval   uint64
	ReportInterval uint64
}

после разделения. Попробую еще раз.

2024-05-16 11:31 UTC, s-shpak requested changes

2024-05-16 11:31 UTC, s-shpak commented on internal/server/api/server_handlers.go
> +		w.WriteHeader(http.StatusNotImplemented)
Лучше просто BadRequest

2024-05-16 15:11 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +	t, err := template.New("All Metrics").Parse(tpl)
Сделал по первому варианту, хотя не уверен что изящно:

type Server struct {
	store   storage.MemStorage
	router  *chi.Mux
	cfg     config.ServerCfg
	tSingle *template.Template
	tAll    *template.Template
}

2024-05-16 15:15 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +		log.Printf("an error occured parsing template: %v", err)
Да, с логикой работы мне еще надо разбираться - где выйти, где идти дальше. После вашего объяснения понятно, что если не получилось разобрать шаблон, то и выводить данные некуда. Сделал так:
			log.Fatalf("an error occured parsing template for all metrics: %v", err)

2024-05-16 15:16 UTC, ilshat-fattakhov commented on internal/storage/storage.go
> +	// mux *sync.Mutex
Удалил

2024-05-16 15:17 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	store  storage.MemStorage
Не могу сказать точно, учусь!

2024-05-16 15:19 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	store  storage.MemStorage
Делал так чтобы не было красных подчеркиваний! :O) Исправил.

2024-05-16 15:19 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	store  storage.MemStorage
Тороплюсь, т.к. завтра жесткий дедлайн!

2024-05-16 15:42 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
> +		w.WriteHeader(http.StatusNotImplemented)
Заменил

2024-05-16 17:00 UTC, s-shpak requested changes

2024-05-16 17:00 UTC, s-shpak commented on internal/server/api/server.go
> +			log.Fatalf("an error occured parsing template for single metric: %v", err)
Фаталиться из глубины кода нельзя, как обсуждали в видео про обработку ошибок

2024-05-16 17:00 UTC, s-shpak commented on internal/server/api/server.go
> +	case "one":
Что если `w` не `one` и не `all` ? Зачем нам два разных темплейта ?

2024-05-16 17:00 UTC, s-shpak commented on internal/server/api/server_handlers.go
>  		log.Printf("an error occured converting template data: %v", err)
Здесь надо вернуть клиенту `InternalServerError` и вызвать `return`: мы не можем продолжить выполнение програмы

2024-05-17 01:37 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +	case "one":
Муки творчества! :O) Исправил.

2024-05-17 01:38 UTC, ilshat-fattakhov commented on internal/server/api/server.go
> +			log.Fatalf("an error occured parsing template for single metric: %v", err)
Да, я смотрел видео, практика у меня разошлась с теорией. Прокинул ошибку до main(), надеюсь правильно

2024-05-17 01:39 UTC, ilshat-fattakhov commented on internal/server/api/server_handlers.go
>  		log.Printf("an error occured converting template data: %v", err)
Спасибо за подсказку!

2024-05-17 08:47 UTC, s-shpak approved these changes

2024-05-17 12:33 UTC, ilshat-fattakhov commented
Merging to main

2024-05-17 12:33 UTC, merged